name: flutter_applicatione
description: "A new Flutter project."

publish_to: "none" # Si tu ne souhaites pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Add intl dependency
  firebase_core: ^3.12.1 # Mise à jour vers la version compatible
  firebase_auth: ^5.5.1
  cloud_firestore: 5.5.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.6
  image_picker: ^0.8.5+3
  firebase_storage: ^12.4.4
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
